---
name: Reportar un error
about: ¿Encontraste un bug? ¡Comunicalo por aquí! 🐛
title: ""
labels: "bug"
---
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo para reportar esto! Completá lo que consideres necesario
  - type: textarea
    id: what-happened
    attributes:
      label: Descripción
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
