name: Reportar un error
description: 쮼ncontraste un bug? 춰Comunicalo por aqu칤! 游냍
title: "[BUG]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Gracias por ayudarnos a mejorar nuestro proyecto. Complet치 lo que consideres necesario
  - type: textarea
    id: what-happened
    attributes:
      label: Describ칤 brevemente lo que est치 sucediendo
      description: Proporcion치 una descripci칩n corta y clara.
      placeholder: "Algo no funciona como se esperaba cuando hago X..."
    validations:
      required: true
